<?php

namespace Cps\Personal\ArchivoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * archivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class archivoRepository extends EntityRepository
{
     public function FiltrarPer($searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT a
                                     FROM CpsPerArchivoBundle:archivo a
                                     where a.nroempleado LIKE '%$searchQuery%' ORDER BY a.id DESC");
        $result = $query->getResult();
        return $result;
    }
    
    public function detalle1($archivo_id){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT d
                                     FROM CpsPerArchivoBundle:detalle d
                                     where d.estado = 1 and d.tipo = 1 and d.archivoc =:valor")
                ->setParameter("valor",$archivo_id);
        $result = $query->getResult();
        return $result;
    }
    public function detalle2($archivo_id){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT d
                                     FROM CpsPerArchivoBundle:detalle d
                                     where d.estado = 1 and d.tipo = 2 and d.archivoc =:valor")
                ->setParameter("valor",$archivo_id);
        $result = $query->getResult();
        return $result;
    }
    public function detalle3($archivo_id){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT d
                                     FROM CpsPerArchivoBundle:detalle d
                                     where d.estado = 1 and d.tipo = 3 and d.archivoc =:valor")
                ->setParameter("valor",$archivo_id);
        $result = $query->getResult();
        return $result;
    }
    public function detalle4($archivo_id){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT d
                                     FROM CpsPerArchivoBundle:detalle d
                                     where d.estado = 1 and d.tipo = 4 and d.archivoc =:valor")
                ->setParameter("valor",$archivo_id);
        $result = $query->getResult();
        return $result;
    }
    public function detalle5($archivo_id){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT d
                                     FROM CpsPerArchivoBundle:detalle d
                                     where d.estado = 1 and d.tipo = 5 and d.archivoc =:valor")
                ->setParameter("valor",$archivo_id);
        $result = $query->getResult();
        return $result;
    }
}
// public function ChequeSearch($usuario, $searchQuery){
//         $emp=$this->getEntityManager();
//         $query = $emp->createQuery("SELECT o.id, c.bte , o.cheque, o.monto, b.nombre, o.estado
//                                      FROM CpschequeBundle:Comprobante c
//                                      JOIN c.cheque o
//                                      JOIN o.benficiario b
//                                      where o.estado <> 3 and o.cheque LIKE '%$searchQuery%' and c.Usuario=:nro ORDER BY c.id DESC")
//                 ->setParameter("nro",$usuario);
//         $result = $query->getResult();
//         return $result;
//     }