<?php

namespace Cps\Personal\ArchivoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * detalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detalleRepository extends EntityRepository
{
}
